import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Logo from '../components/Logo'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Shortenr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
    <Logo></Logo>

    </div>
  )
}

export default Home
